[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run db:generate && npm run build"

[deploy]
startCommand = "bash -c 'source ./Docker/scripts/deploy_database.sh && npm run start:prod'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
